theme: jekyll-theme-minimal
title: Nekochan's Digital Diary
description: A personal space for memories and experiences
show_downloads: false
google_analytics: false
baseurl: /
logo: /assets/images/avatar.jpg
